add_library(chai SHARED IMPORTED)

if(WIN32)
	set_target_properties(chai PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/include")
	if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
		set_target_properties(chai PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/bin64/chai.dll;${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/bin64/ftd2xx.dll")
		set_target_properties(chai PROPERTIES IMPORTED_IMPLIB   "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/lib64/chai.lib")
	else()
		set_target_properties(chai PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/bin32/chai.dll;${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/bin32/ftd2xx.dll")
		set_target_properties(chai PROPERTIES IMPORTED_IMPLIB   "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-windows/lib32/chai.lib")
	endif()
else()
	set_target_properties(chai PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-linux/include")
	if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "8")
		set_target_properties(chai PROPERTIES IMPORTED_LOCATION "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-linux/lib64/libchai.so")
		set_target_properties(chai PROPERTIES IMPORTED_IMPLIB   "${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/marathon-linux/lib64/libchai.so")
	else()
		message(FATAL_ERROR "marathon: Linux 32-bit is not supported")
	endif()
endif()
